# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

clamping <- function(img) {
    .Call('_Kaleido_clamping', PACKAGE = 'Kaleido', img)
}

im_height <- function(img) {
    .Call('_Kaleido_im_height', PACKAGE = 'Kaleido', img)
}

im_width <- function(img) {
    .Call('_Kaleido_im_width', PACKAGE = 'Kaleido', img)
}

im_nc <- function(img) {
    .Call('_Kaleido_im_nc', PACKAGE = 'Kaleido', img)
}

im_npix <- function(img) {
    .Call('_Kaleido_im_npix', PACKAGE = 'Kaleido', img)
}

im_rep <- function(img) {
    .Call('_Kaleido_im_rep', PACKAGE = 'Kaleido', img)
}

feather <- function(img) {
    .Call('_Kaleido_feather', PACKAGE = 'Kaleido', img)
}

nostalgia <- function(img) {
    .Call('_Kaleido_nostalgia', PACKAGE = 'Kaleido', img)
}

lighting <- function(img, centerx = 0.5, centery = 0.5, strength = 0.5) {
    .Call('_Kaleido_lighting', PACKAGE = 'Kaleido', img, centerx, centery, strength)
}

fleetingtime <- function(img) {
    .Call('_Kaleido_fleetingtime', PACKAGE = 'Kaleido', img)
}

sketcher <- function(img, ksize = 15L, cont = 5L, sigma = 50) {
    .Call('_Kaleido_sketcher', PACKAGE = 'Kaleido', img, ksize, cont, sigma)
}

